#pragma once
#include "vector.hpp"

#include "IClientMode.hpp"
#include "CHLClient.hpp"
#include "ISurface.hpp"
#include "IPanel.hpp"
#include "IVEngineClient.hpp"
#include "IClientEntityList.hpp"
#include "GlobalVars_t.hpp"
#include "IPrediction.hpp"
#include "ICvar.hpp"
#include "IVModelInfoClient.hpp"
#include "IMaterialSystem.hpp"
#include "IEngineTrace.hpp"
#include "IVRenderView.hpp"
#include "IPhysicsSurfaceProps.hpp"
#include "CUtlVector.hpp"
#include "IMemAlloc.hpp"
#include "IGameEventManager.hpp"
#include "KeyValues.hpp"
#include "CInput.hpp"
#include "bf_write.hpp"
#include "match_framework.h"


#include "c_base_player.hpp"
#include "ISteamClient.hpp"