#pragma once

enum MoveType_t {
	MOVETYPE_NONE = 0,
	MOVETYPE_ISOMETRIC,
	MOVETYPE_WALK,
	MOVETYPE_STEP,
	MOVETYPE_FLY,
	MOVETYPE_FLYGRAVITY,
	MOVETYPE_VPHYSICS,
	MOVETYPE_PUSH,
	MOVETYPE_NOCLIP,
	MOVETYPE_LADDER,
	MOVETYPE_OBSERVER,
	MOVETYPE_CUSTOM,

	MOVETYPE_LAST = MOVETYPE_CUSTOM,

	MOVETYPE_MAX_BITS = 4,
};

enum TFConditions_t {
	TFCond_Slowed = ( 1 << 0 ),
	TFCond_Zoomed = ( 1 << 1 ),
	TFCond_Disguising = ( 1 << 2 ),
	TFCond_Disguised = ( 1 << 3 ),
	TFCond_Cloaked = ( 1 << 4 ),
	TFCond_Ubercharged = ( 1 << 5 ),
	TFCond_TeleportedGlow = ( 1 << 6 ),
	TFCond_Taunting = ( 1 << 7 ),
	TFCond_UberchargeFading = ( 1 << 8 ),
	TFCond_CloakFlicker = ( 1 << 9 ),
	TFCond_Teleporting = ( 1 << 10 ),
	TFCond_Kritzkrieged = ( 1 << 11 ),
	TFCond_TmpDamageBonus = ( 1 << 12 ),
	TFCond_DeadRingered = ( 1 << 13 ),
	TFCond_Bonked = ( 1 << 14 ),
	TFCond_Stunned = ( 1 << 15 ),
	TFCond_Buffed = ( 1 << 16 ),
	TFCond_Charging = ( 1 << 17 ),
	TFCond_DemoBuff = ( 1 << 18 ),
	TFCond_CritCola = ( 1 << 19 ),
	TFCond_InHealRadius = ( 1 << 20 ),
	TFCond_Healing = ( 1 << 21 ),
	TFCond_OnFire = ( 1 << 22 ),
	TFCond_Overhealed = ( 1 << 23 ),
	TFCond_Jarated = ( 1 << 24 ),
	TFCond_Bleeding = ( 1 << 25 ),
	TFCond_DefenseBuffed = ( 1 << 26 ),
	TFCond_Milked = ( 1 << 27 ),
	TFCond_MegaHeal = ( 1 << 28 ),
	TFCond_RegenBuffed = ( 1 << 29 ),
	TFCond_MarkedForDeath = ( 1 << 30 ),
	TFCond_NoHealingDamageBuff = ( 1 << 31 ),

	TFCondEx_SpeedBuffAlly = ( 1 << 0 ),
	TFCondEx_HalloweenCritCandy = ( 1 << 1 ),
	TFCondEx_CritCanteen = ( 1 << 2 ),
	TFCondEx_CritDemoCharge = ( 1 << 3 ),
	TFCondEx_CritHype = ( 1 << 4 ),
	TFCondEx_CritOnFirstBlood = ( 1 << 5 ),
	TFCondEx_CritOnWin = ( 1 << 6 ),
	TFCondEx_CritOnFlagCapture = ( 1 << 7 ),
	TFCondEx_CritOnKill = ( 1 << 8 ),
	TFCondEx_RestrictToMelee = ( 1 << 9 ),
	TFCondEx_DefenseBuffNoCritBlock = ( 1 << 10 ),
	TFCondEx_Reprogrammed = ( 1 << 11 ),
	TFCondEx_PyroCrits = ( 1 << 12 ),
	TFCondEx_PyroHeal = ( 1 << 13 ),
	TFCondEx_FocusBuff = ( 1 << 14 ),
	TFCondEx_DisguisedRemoved = ( 1 << 15 ),
	TFCondEx_MarkedForDeathSilent = ( 1 << 16 ),
	TFCondEx_DisguisedAsDispenser = ( 1 << 17 ),
	TFCondEx_Sapped = ( 1 << 18 ),
	TFCondEx_UberchargedHidden = ( 1 << 19 ),
	TFCondEx_UberchargedCanteen = ( 1 << 20 ),
	TFCondEx_HalloweenBombHead = ( 1 << 21 ),
	TFCondEx_HalloweenThriller = ( 1 << 22 ),
	TFCondEx_BulletCharge = ( 1 << 26 ),
	TFCondEx_ExplosiveCharge = ( 1 << 27 ),
	TFCondEx_FireCharge = ( 1 << 28 ),
	TFCondEx_BulletResistance = ( 1 << 29 ),
	TFCondEx_ExplosiveResistance = ( 1 << 30 ),
	TFCondEx_FireResistance = ( 1 << 31 ),

	TFCondEx2_Stealthed = ( 1 << 0 ),
	TFCondEx2_MedigunDebuff = ( 1 << 1 ),
	TFCondEx2_StealthedUserBuffFade = ( 1 << 2 ),
	TFCondEx2_BulletImmune = ( 1 << 3 ),
	TFCondEx2_BlastImmune = ( 1 << 4 ),
	TFCondEx2_FireImmune = ( 1 << 5 ),
	TFCondEx2_PreventDeath = ( 1 << 6 ),
	TFCondEx2_MVMBotRadiowave = ( 1 << 7 ),
	TFCondEx2_HalloweenSpeedBoost = ( 1 << 8 ),
	TFCondEx2_HalloweenQuickHeal = ( 1 << 9 ),
	TFCondEx2_HalloweenGiant = ( 1 << 10 ),
	TFCondEx2_HalloweenTiny = ( 1 << 11 ),
	TFCondEx2_HalloweenInHell = ( 1 << 12 ),
	TFCondEx2_HalloweenGhostMode = ( 1 << 13 ),
	TFCondEx2_Parachute = ( 1 << 16 ),
	TFCondEx2_BlastJumping = ( 1 << 17 ),

	TFCond_MiniCrits = ( TFCond_Buffed | TFCond_CritCola ),
	TFCond_IgnoreStates = ( TFCond_Ubercharged | TFCond_Bonked ),
	TFCondEx_IgnoreStates = ( TFCondEx_PyroHeal )
};